### ISSUE TITLE
Error: Less than two common wavelengths in Reference Image

### ISSUE THREAD

**Issue by naureeng** [macronucleus/chromagnon#18] opened 2019-05-08 18:29 UTC
My reference image is of beads in the two wavelengths (561 and 647). The wavelengths in the program come up as 400 and 550. In the target image, there is a range of values from 400 to 647.
How come one stack comes up with 2 values in wavelength and the other as a range? I would like to proceed with your Chromagnon code but currently cannot with the error. 

![error](https://user-images.githubusercontent.com/32179063/57398709-955f6b80-71c7-11e9-92b9-b1233f9868ee.PNG)

**Comment by macronucleus** [comment] 2019-05-09 03:24
Thank you for reporting the error. I am sure it's an error to read the metadata of your tif file. I am sorry. I need to look at the header of your tif file. Would you share your image file with me?
You can use this URL to send your file safely to me.
https://fexcc.nict.go.jp/user/~th/t2rofjgs0mqmm4554cc90363m0
The password is F5C4LTevma

**Comment by naureeng** [comment] 2019-05-09 08:37
Thank you so much, that is very considerate of you! I look forward to using your code. I've sent the file.

**Comment by macronucleus** [comment] 2019-05-09 09:23
Thanks a lot for sharing the image file. Actually, the output of wavelengths 400 and 550 is okay. This is the expected behavior when channel information was not found in the header (very common for tif files). In fact, as far as I can see, there was no channel description in your file '561_647_composite.tif' (correct me if this is wrong). So, please don't care about 400 and 550, it's just a tentative names for channels. This should work as long as the order of the channels in the target files are the same as the reference file.
I think the problem is the sequence of channel names in your target files. Possibly, time or Z is read as channels. Could you check if number of channels are actually two in the target images? If it is correct, is it possible to share the target file with me? You can use the same URL above again.
Thank you for your help.

**Comment by naureeng** [comment] 2019-05-09 12:12
Dear Atsushi,
Thank you so much for your time and help. I shared the target file (it has a range of values that includes 400 but not 550).
Best,
Naureen

**Comment by macronucleus** [comment] 2019-05-13 07:00
Dear Naureen,
I don't know so much detail about tiff files, but as far as I know, your target file does not seem to have the right header information. The metadata look like a composite color image of 27 channels with a single Z slice and a single time frame. However, the image looks like a single color Z stack of 27 optical slices.

My ImageJ (Fiji) could not open your file, either. 
What does your software, which created this image file, say for number of channels, Z slices and time frames?
Can you go back to the original file and create your image file using ImageJ?
Atsushi

**Comment by naureeng** [comment] 2019-05-13 09:53
Dear Atsushi,

Thanks for the reply! I made a Composite image on ImageJ and it works (2 wavelengths). However, when I try to automate this in my MATLAB code and create a tiff stack (3 channels = 2 channels of data and 1 is blank), this image is not recognized by Chromagnon (cannot drag and drop/ open) but works fine in ImageJ.

**Comment by macronucleus** [comment] 2019-05-14 02:28
Dear Naureen,
I confirmed the issue. Chromagnon failed to read your composite tiff stack, which has a perfect header.
While fixing the problem, would you use ImageJ to make your target files?
Another possibility is to make non-composite tiff files by your MATALB if possible; this should work at this moment.
It may take some time to release the new binary version.

I will comment here when the new binary version is available.
Thank you! --- Atsushi

**Comment by naureeng** [comment] 2019-05-14 08:02
Dear Atsushi,

Thank you so much for your help and time so far! I am very grateful. Of course, I will use an ImageJ macro to make those composite images in batch.

Best,
Naureen

**Comment by macronucleus** [comment] 2019-06-10 06:20
I just released the new version (v0.80) which is capable of handling your tiff files. I am sorry that it took so long. I will close this issue but please re-open if you have any related problems in the new version. Thank you.

**Closed as completed by macronucleus** 2019-06-10 06:20 UTC

**Comment by naureeng** [comment] 2019-06-11 10:48
Incredible, thank you so much!
